# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD Docker

# 환경변수
env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/vote-api-server-img
  DOCKER_CONTAINER: vote-api-server

# 이벤트
on:
  push:
    branches: [main]

jobs:
  # 도커 이미지 빌드
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login ghcr
        uses: docker/login-action@v2
        with:
          repostry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  # EC2 배포
  deploy:
    needs: build
    runs-on: [self-hosted, label-vote]

    steps:
      - name: Login ghcr
        uses: docker/login-action@v2
        with:
          repostry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run docker
      - run: /
          docker stop ${{ env.DOCKER_CONTAINER }} && docker rm ${{ env.DOCKER_CONTAINER }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 80:3000 --name ${{ env.DOCKER_CONTAINER }} --restart always ${{ env.DOCKER_IMAGE }}:latest
